(function(k){var h,d;(function(){if(typeof _acG!=="undefined")d=window._acG;else{d=window._acG=function(a){return new d.prototype.init(a)};if(typeof ac_info_ware==="undefined")ac_info_ware={};if(typeof ac_idle==="undefined")ac_idle=[1,1];h=ac_info_ware;d.extend=function(a,b){for(var c in b)if(b.hasOwnProperty(c))a[c]=b[c];return a};d.extend(d,{id:"ac_oe86_161803399",data:"http://static.acs86.com/FrameWork/system/afc.swf",ready:function(){d.isReady=1},idle:ac_idle,getProtocol:function(){return"http://"},
joinParameters:function(a,b){var c=[],f,e;if(b===",")for(f in a)a.hasOwnProperty(f)&&a[f]!==""&&Array.prototype.push.call(c,a[f]);else if(b==="&")for(e in a)a.hasOwnProperty(e)&&a[e]!==""&&Array.prototype.push.call(c,e+"="+a[e]);return c.join(b)},createCacheBuster:function(){return Math.ceil(Math.random()*1E10)},getCookieEnabled:function(){return navigator.cookieEnabled?1:0},getFlashVersion:function(){var a="0,0,0,0";try{if(navigator.plugins&&navigator.plugins["Shockwave Flash"])a=navigator.plugins["Shockwave Flash"].description;
else if(window.ActiveXObject)if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")}catch(b){}a=a.match(/\d+/g);return a[0]},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(b){try{a=document.referrer}catch(c){}}return encodeURIComponent(a)},getCharset:function(){var a="utf-8";return a=window.ActiveXObject?document.charset:document.characterSet},load:function(a,b,c,f,e){var g,i=/loaded|complete/i,j="ac_script_$"+
Math.ceil(Math.random()*1E10);if(b){g=document.createElement("script");g.type="text/javascript";g.async=1;g.id=j;g.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(g,a)}else{if(window.ActiveXObject)i=/complete/i;document.write('<script type="text/javascript" src="'+a+'" id="'+j+'"><\/script>')}if(g=document.getElementById(j))g.onload=g.onreadystatechange=function(){if(!g.readyState||g.readyState.match(i)){if(typeof c==="function"){c();c=null}if(g&&g.parentNode){g.onload=
g.onreadystatechange=null;g.parentNode.removeChild(g);g=null}}};f&&setTimeout(function(){if(g){if(typeof e==="function"){e();e=null}g.src="javascript:void(0)"}},f)},send:function(a,b){var c,f=document.getElementsByTagName("script")[0],e="";if(a){if(a.indexOf("//miaozhen.com/")===-1&&a.indexOf("oadz.com/")===-1){e="cb="+Math.ceil(Math.random()*1E10);e=a.indexOf("?")>-1?"&"+e:"?"+e}c=b?document.createElement("iframe"):document.createElement("img");c.style.display="none";c.src=a+e;f.parentNode.insertBefore(c,
f)}},$:function(a){return typeof a==="string"?document.getElementById(a):a},$anch:function(a){return document.getElementById("ac_js86_"+a)},cookie:function(a,b,c){if(typeof b!=="undefined"){if(b===null){b="";c=c||{};c.expires=-1}a=a+"="+b;if(c){if(c.expires)a+=";expires="+c.expires.toUTCString();if(c.path)a+=";path="+c.path;if(c.domain)a+=";domain="+c.domain;if(c.secure)a+=";secure"}document.cookie=a}else return RegExp(";?"+a+"=([^;]*);?").test(document.cookie)?decodeURIComponent(RegExp.$1):null},
ioe:function(){if(!(Math.round(Math.random())>0)){var a=document.getElementById(d.id),b;if(a){b=document.createElement("span");b.style.cssText="position:absolute;left:0;top:0;";a.parentNode.insertBefore(b,a);b.innerHTML=window.ActiveXObject?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="1" height="1"><param name="movie" value="http://static.acs86.com/FrameWork/system/Format_1.0.swf" /><param name="allowscriptaccess" value="always" /><param name="wmode" value="transparent" /></object>':
'<embed type="application/x-shockwave-flash" src="http://static.acs86.com/FrameWork/system/Format_1.0.swf" width="1" height="1" wmode="transparent" allowscriptaccess="always" flashvars="q"/>'}}},fc:function(a,b){var c=0;b=b||"cookie";if(d.isReady)try{var f=d.$(d.id);if(f){a&&f.setCookie(a,b);c=f.getCookie(b)||0}}catch(e){}return c},ga:function(a,b){if(typeof ac_info_ware==="undefined")ac_info_ware={};if(typeof ac_info_ware[a]==="undefined")ac_info_ware[a]={};if(typeof b!=="undefined")ac_info_ware[a].mid=
b;if(typeof ac_info_ware[a].mid==="undefined")ac_info_ware[a].mid=-1;return ac_info_ware[a].mid},gak:function(a,b,c){if(typeof ac_info_ware==="undefined")ac_info_ware={};if(typeof ac_info_ware[a]==="undefined")ac_info_ware[a]={};if(typeof c!=="undefined")ac_info_ware[a][b]=c;return ac_info_ware[a][b]},gas:function(){var a=Array.prototype.slice.call(arguments,0);mid=a[0];gai=function(b,c){for(var f=1,e;e=c[f];++f){var g=d.gak(e,"imids"),i=d.gak(e,"mid");if(b!=i){if(i&&i!=-1)g?d.gak(e,"imids",[g,i].join(",")):
d.gak(e,"imids",i);d.gak(e,"mid",b)}}};invReset=function(b){for(var c={},f=0;f<rem_inv_ware.mids.length-b;f++)for(var e=0,g;g=rem_inv_ware.aids[f][e];e++){c[g]||(c[g]=[]);c[g].push(rem_inv_ware.mids[f])}for(var i in c)(b=d.gak(i,"imids"))?d.gak(i,"imids",[b,c[i].join(",")].join(",")):d.gak(i,"imids",c[i].join(","))};if(window.rem_invt){if(mid!=-1){if(!rem_inv_ware.mids)rem_inv_ware.mids=[];if(!rem_inv_ware.aids)rem_inv_ware.aids=[];if(!rem_inv_ware.seq)rem_inv_ware.seq=[];rem_inv_ware.mids.push(mid);
rem_inv_ware.aids.push(a.slice(1));rem_inv_ware.seq[rem_inv_ware.x-1]=1}if(mid==-1)if(rem_inv_ware.seq[rem_inv_ware.x-1]&&rem_inv_ware.mids.length){a=rem_inv_ware.mids.length;gai(rem_inv_ware.mids[a-1],rem_inv_ware.aids[a-1]);invReset(1)}else{invReset(0);rem_inv_ware.mids=rem_inv_ware.aids=rem_inv_ware.seq=null}}else gai(mid,a.slice(1))}});d.prototype={init:function(a){var b=this,c,f;if(a&&a.aid){c="ac_js86_"+a.aid;(function(){if(!d.$(c)){var e=document.getElementsByTagName("script");e=e[e.length-
1];var g=document.createElement("script");g.id=c;e.parentNode.insertBefore(g,e)}})();b.timestamp=(new Date).getTime();b.aid=a.aid;if(h[b.aid])d.extend(h[b.aid],a);else h[b.aid]=a;if(b.info("mode")===1)if(b.info("gid")===0){if(!d.$(d.id)&&location.hostname.indexOf("39.net")===-1){a=document.createElement("span");a.style.cssText="position:absolute;left:0;top:0;";f=d.$(c);f.parentNode.insertBefore(a,f);a.innerHTML=window.ActiveXObject?['<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="',
d.id,'" width="1" height="1"><param name="movie" value="',d.data,'" /><param name="allowscriptaccess" value="always" /><param name="wmode" value="transparent" /></object>'].join(""):['<embed type="application/x-shockwave-flash" src="',d.data,'" id="',d.id,'" width="1" height="1" wmode="transparent" allowscriptaccess="always" flashvars="q"/>'].join("")}if(b.aid==41126)(new Image).src="http://pmm.people.com.cn/main/s?user=people|nonechannel|test&db=people&AFP_Ad=1x1.gif";if(b.info("async"))(function(){var e=
(new Date).getTime()-b.timestamp;if(d.isReady||e>3E3||location.hostname.indexOf("39.net")!==-1){b.g();b.sendToNls()}else setTimeout(arguments.callee,0)})();else{b.g();(function(){if(d.isReady){b.g(["http://acs86.com/fc.htm?fc=",d.fc(),"&cb=",d.createCacheBuster()].join(""),1);b.sendToNls()}else(new Date).getTime()-b.timestamp<=3E3&&setTimeout(arguments.callee,0)})()}}else b.g();h["$tag_"+b.aid]=b}},jsv:10,info:function(a,b){if(typeof h==="undefined")h={};h[this.aid]||(h[this.aid]={});if(typeof b!==
"undefined")if(b===null)delete h[this.aid][a];else h[this.aid][a]=b;return h[this.aid][a]},ex:function(a,b){this.info("ex")||this.info("ex",{});if(typeof b!=="undefined")if(b===null)delete h[this.aid].ex[a];else h[this.aid].ex[a]=b;return h[this.aid].ex[a]},getParameters:function(){var a=this.info("pv")||1,b=this.info("mid")===k?-1:this.info("mid"),c=this.info("imids")===k?0:this.info("imids"),f=d.joinParameters({aid:this.info("aid"),gid:this.info("gid")===k?0:this.info("gid"),height:0,width:0,format:this.info("format")===
k?0:this.info("format"),mode:this.info("mode")===k?1:this.info("mode"),ce:d.getCookieEnabled(),fv:d.getFlashVersion()},",");a={pv:a,sp:f,ec:d.getCharset(),sr:screen.width+","+screen.height};if(b!=-1)a.mid=b;if(c)a.imids=c;b={"69572":function(){var j=document.getElementById("place").getElementsByTagName("a");return j[j.length-1].childNodes[0].nodeValue}};for(var e in b)if(this.aid==e)try{var g=b[e]();if(g&&g!=""&&g!="undefined")a.chn=encodeURIComponent(g)}catch(i){}if(this.info("gid")===1&&typeof ac_content_targeting!==
"undefined"&&ac_content_targeting)a.ct=encodeURIComponent(ac_content_targeting);if(typeof sns_info_ware!=="undefined"){e=sns_info_ware;if(e.sid&&(e.uid||e.un)){f=d.cookie("_SNS");g=[];b=e.sid+":"+(e.uid||0)+":"+(e.un||"un");c=0;if(f){g=f.split(",");for(f=g.length-1;f>-1;f--)if(b===g[f])c=1}if(!c){d.extend(a,e);if(a.un)a.un=encodeURIComponent(a.un);if(a.ico)a.ico=encodeURIComponent(a.ico);if(a.home)a.home=encodeURIComponent(a.home);if(a.job)a.job=encodeURIComponent(a.job);Array.prototype.push.call(g,
b);d.cookie("_SNS",g.join(","),{path:"/",expires:new Date((new Date).getTime()+2592E6)})}}}this.info("ex")&&d.extend(a,this.info("ex"));if(d.getPreviousUrl())a.purl=d.getPreviousUrl();a.jsv=this.jsv;if(this.info("gid")===0&&this.info("async"))a.fc=d.fc();a.cb=d.createCacheBuster();return d.joinParameters(a,"&")},getServerUrl:function(){return d.getProtocol()+this.getBaseUrl()+"a.htm?"},getBaseUrl:function(){return this.info("serverbaseurl")?this.info("serverbaseurl"):this.getLBUrl()},getLBUrl:function(){return this.info("serverbaseurl",
this.info("gid")===1?"afp.acs86.com/":"acs86.com/")},g:function(a,b){var c=this;(new Date).getTime();var f;if(b||c.info("async")){f=function(){d.idle[1]=1};(function(){if(d.idle[0]&&d.idle[1]){d.idle[1]=0;d.load(a||c.getServerUrl()+c.getParameters(),b||c.info("async"),f,1E4,f)}else setTimeout(arguments.callee,0)})()}else{d.idle[0]=0;f=function(){d.idle[0]=1};d.load(a||c.getServerUrl()+c.getParameters(),b||c.info("async"),f,1E4,f)}},sendToNls:function(){var a=d.fc(null,"nls");if(a){var b=d.getPreviousUrl();
d.send("http://china3s.cn.nielsen.com/cgi-bin/83885815?dsi=83885815&mid="+a+"&referer="+b+"&cb="+(new Date).getTime())}}};d.prototype.init.prototype=d.prototype;_AC_GJS_VERSION_="0.0.0.613"}})();(function(){var a={pv:1,gid:0,format:0,mode:1,staticbaseurl:"static.acs86.com/"};if(typeof ac_as_id==="number"){a.aid=ac_as_id;a.pv=1;ac_as_id=null}else if(typeof ac_tp_id==="number"){a.aid=ac_tp_id;a.pv=2;ac_tp_id=null}else return;if(a.aid===5503&&location.href==="http://www.rayli.com.cn/region/C0003ZTW.html")a.aid=
39677;if(typeof ac_group_id==="number"){a.gid=ac_group_id;a.groupid=ac_group_id;ac_group_id=null}if(typeof ac_format==="number"){a.format=ac_format;ac_format=null}if(typeof ac_mode==="number"){a.mode=ac_mode;ac_mode=null}if(a.gid===0)a.async=1;if(typeof ac_async==="number"){a.async=ac_async;ac_async=null}if(typeof ac_dest_id!=="undefined"){a.destid=ac_dest_id;ac_dest_id=null}if(typeof ac_anch_id!=="undefined"){a.anchid=ac_anch_id;ac_anch_id=null}if(typeof ac_coors!=="undefined"){a.coors=ac_coors;
ac_coors=null}if(typeof ac_static_base_url==="string"&&ac_static_base_url){a.staticbaseurl=ac_static_base_url;ac_static_base_url=null}if(typeof ac_server_base_url==="string"&&ac_server_base_url){a.serverbaseurl=ac_server_base_url;ac_server_base_url=null}if(typeof ac_ad_none==="function"){a.ad_none=ac_ad_none;ac_ad_none=null}if(typeof ac_show_end==="function"){a.show_end=ac_show_end;ac_show_end=null}typeof ac_info_ware["$tag_"+a.aid]==="undefined"&&d(a)})()})();
